### ISSUE TITLE
Schetsen (3 maken)

### ISSUE THREAD

**Issue by driezie** [driezie/connect-your-tribe-squad-page#3]

**Comment by driezie** [comment]
12 feb | We moeten 6 verschillende schetsen maken om een ontwerp te maken en inspiratie op te wekken om dit te maken.

**Comment by Remy2072** [comment]
![Image](https://github.com/driezie/connect-your-tribe-squad-page/assets/70781820/a90b9111-e0bf-4b8e-87c5-6eb213e18a8f)

**Comment by Remy2072** [comment]
![Image](https://github.com/driezie/connect-your-tribe-squad-page/assets/70781820/1d949457-4a45-4864-bc80-8601519bc842)

**Comment by driezie** [comment]
![Image](https://github.com/driezie/connect-your-tribe-squad-page/assets/80174866/9c61a730-2313-496f-8089-8ed9b0eaf3b6)
